### ISSUE TITLE
HEP plugin

### ISSUE THREAD

**Issue by Tsibbie** [hydrology-tep/hep-qgis-plugin-lite#1]
![hep](https://user-images.githubusercontent.com/36195991/35862009-6654f862-0b4a-11e8-9d69-0a7e70d365c6.GIF)

where can I download this plugin?

**Comment by joaandrade** [comment]
The version of the plugin that is in the image cannot be downloaded. That version of the plugin is available within the VMs created with the WOIS template.

To install on a local instance of QGIS, only the **lite version** (that can be downloaded from this repository) is available. The lite version only has available the option "Export model to TEP" and will ask for the IP and password of a WOIS VM. To export a model from the local QGIS using the lite version of the plugin, a WOIS VM is always required.

Hope this helps.
João

**Comment by Tsibbie** [comment]
Thanks. How do I access the VMs ?


Regards,


Tsitsi

________________________________

**Comment by joaandrade** [comment]
If you have an account on cloud.terradue.com, you need to ask them to have the WOIS template available. With this template you will be able to create a new VM.

**Comment by Tsibbie** [comment]
Thanks. I will try to contact them regards,


Tsitsi

________________________________

**Comment by joaandrade** [comment]
You're welcome

**Comment by joaandrade** [comment]
Dear Tsitsi,

HEP is currently working with ESA sponsored users (early adopters) so, you can send a description of your application idea to hydrology-tep@esa.int (or https://hydrology-tep.eo.esa.int/#!contact), if you are interested to apply for later stage.

Regards,
João

**Comment by Tsibbie** [comment]
Thank you very much. I will contact them.


Regards,


Tsitsi

________________________________
